export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta charSet="utf-8" />
      <meta name="description" content="asdasada" />
      <meta name="author" content="Heyshop" />
      <link rel="apple-touch-icon" id="favicon-apple" href="" />
      <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1" />
      <meta name="theme-color" content="#000000" />
      <meta property="og:title" content="nextjs" />
      <meta property="og:type" content="article" />
      <meta property="og:image" content="" />
      <meta property="og:url" content="" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta property="og:description" content="" />
      <title>Nextjs</title>
    </>
  )
}
